// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: matchmaking.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Matchmaking_CreateGame_FullMethodName = "/foolcard.v1.Matchmaking/CreateGame"
	Matchmaking_JoinGame_FullMethodName   = "/foolcard.v1.Matchmaking/JoinGame"
)

// MatchmakingClient is the client API for Matchmaking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Быстрая игра — только через Session.QuickMatch, не unary.
type MatchmakingClient interface {
	CreateGame(ctx context.Context, in *PlayerProfile, opts ...grpc.CallOption) (*CreateGameResponse, error)
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error)
}

type matchmakingClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakingClient(cc grpc.ClientConnInterface) MatchmakingClient {
	return &matchmakingClient{cc}
}

func (c *matchmakingClient) CreateGame(ctx context.Context, in *PlayerProfile, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, Matchmaking_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGameResponse)
	err := c.cc.Invoke(ctx, Matchmaking_JoinGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchmakingServer is the server API for Matchmaking service.
// All implementations must embed UnimplementedMatchmakingServer
// for forward compatibility.
//
// Быстрая игра — только через Session.QuickMatch, не unary.
type MatchmakingServer interface {
	CreateGame(context.Context, *PlayerProfile) (*CreateGameResponse, error)
	JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error)
	mustEmbedUnimplementedMatchmakingServer()
}

// UnimplementedMatchmakingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchmakingServer struct{}

func (UnimplementedMatchmakingServer) CreateGame(context.Context, *PlayerProfile) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedMatchmakingServer) JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedMatchmakingServer) mustEmbedUnimplementedMatchmakingServer() {}
func (UnimplementedMatchmakingServer) testEmbeddedByValue()                     {}

// UnsafeMatchmakingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakingServer will
// result in compilation errors.
type UnsafeMatchmakingServer interface {
	mustEmbedUnimplementedMatchmakingServer()
}

func RegisterMatchmakingServer(s grpc.ServiceRegistrar, srv MatchmakingServer) {
	// If the following call pancis, it indicates UnimplementedMatchmakingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Matchmaking_ServiceDesc, srv)
}

func _Matchmaking_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matchmaking_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServer).CreateGame(ctx, req.(*PlayerProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Matchmaking_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matchmaking_JoinGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServer).JoinGame(ctx, req.(*JoinGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Matchmaking_ServiceDesc is the grpc.ServiceDesc for Matchmaking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Matchmaking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foolcard.v1.Matchmaking",
	HandlerType: (*MatchmakingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _Matchmaking_CreateGame_Handler,
		},
		{
			MethodName: "JoinGame",
			Handler:    _Matchmaking_JoinGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchmaking.proto",
}
