// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: session.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameSession_Session_FullMethodName = "/foolcard.v1.GameSession/Session"
)

// GameSessionClient is the client API for GameSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameSessionClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type gameSessionClient struct {
	cc grpc.ClientConnInterface
}

func NewGameSessionClient(cc grpc.ClientConnInterface) GameSessionClient {
	return &gameSessionClient{cc}
}

func (c *gameSessionClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameSession_ServiceDesc.Streams[0], GameSession_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameSession_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// GameSessionServer is the server API for GameSession service.
// All implementations must embed UnimplementedGameSessionServer
// for forward compatibility.
type GameSessionServer interface {
	Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedGameSessionServer()
}

// UnimplementedGameSessionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameSessionServer struct{}

func (UnimplementedGameSessionServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedGameSessionServer) mustEmbedUnimplementedGameSessionServer() {}
func (UnimplementedGameSessionServer) testEmbeddedByValue()                     {}

// UnsafeGameSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameSessionServer will
// result in compilation errors.
type UnsafeGameSessionServer interface {
	mustEmbedUnimplementedGameSessionServer()
}

func RegisterGameSessionServer(s grpc.ServiceRegistrar, srv GameSessionServer) {
	// If the following call pancis, it indicates UnimplementedGameSessionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameSession_ServiceDesc, srv)
}

func _GameSession_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameSessionServer).Session(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameSession_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// GameSession_ServiceDesc is the grpc.ServiceDesc for GameSession service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameSession_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foolcard.v1.GameSession",
	HandlerType: (*GameSessionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _GameSession_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "session.proto",
}
