// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuickMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AvatarId      int32                  `protobuf:"varint,2,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickMatch) Reset() {
	*x = QuickMatch{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickMatch) ProtoMessage() {}

func (x *QuickMatch) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickMatch.ProtoReflect.Descriptor instead.
func (*QuickMatch) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *QuickMatch) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *QuickMatch) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *Subscribe) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Subscribe) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *Kick) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type StartGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

type PlayCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	TargetPairId  *int32                 `protobuf:"varint,2,opt,name=target_pair_id,json=targetPairId,proto3,oneof" json:"target_pair_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCard) Reset() {
	*x = PlayCard{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCard) ProtoMessage() {}

func (x *PlayCard) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCard.ProtoReflect.Descriptor instead.
func (*PlayCard) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *PlayCard) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PlayCard) GetTargetPairId() int32 {
	if x != nil && x.TargetPairId != nil {
		return *x.TargetPairId
	}
	return 0
}

type AddCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCard) Reset() {
	*x = AddCard{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCard) ProtoMessage() {}

func (x *AddCard) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCard.ProtoReflect.Descriptor instead.
func (*AddCard) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *AddCard) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type Pass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pass) Reset() {
	*x = Pass{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pass) ProtoMessage() {}

func (x *Pass) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pass.ProtoReflect.Descriptor instead.
func (*Pass) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

type Bito struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bito) Reset() {
	*x = Bito{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bito) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bito) ProtoMessage() {}

func (x *Bito) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bito.ProtoReflect.Descriptor instead.
func (*Bito) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

type Leave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leave) Reset() {
	*x = Leave{}
	mi := &file_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leave) ProtoMessage() {}

func (x *Leave) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leave.ProtoReflect.Descriptor instead.
func (*Leave) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{9}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{10}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_QuickMatch
	//	*ClientMessage_Subscribe
	//	*ClientMessage_Kick
	//	*ClientMessage_StartGame
	//	*ClientMessage_PlayCard
	//	*ClientMessage_AddCard
	//	*ClientMessage_Pass
	//	*ClientMessage_Bito
	//	*ClientMessage_Ready
	//	*ClientMessage_Leave
	//	*ClientMessage_Ping
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{11}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetQuickMatch() *QuickMatch {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_QuickMatch); ok {
			return x.QuickMatch
		}
	}
	return nil
}

func (x *ClientMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientMessage) GetKick() *Kick {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

func (x *ClientMessage) GetStartGame() *StartGame {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_StartGame); ok {
			return x.StartGame
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayCard() *PlayCard {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayCard); ok {
			return x.PlayCard
		}
	}
	return nil
}

func (x *ClientMessage) GetAddCard() *AddCard {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_AddCard); ok {
			return x.AddCard
		}
	}
	return nil
}

func (x *ClientMessage) GetPass() *Pass {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Pass); ok {
			return x.Pass
		}
	}
	return nil
}

func (x *ClientMessage) GetBito() *Bito {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Bito); ok {
			return x.Bito
		}
	}
	return nil
}

func (x *ClientMessage) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ClientMessage) GetLeave() *Leave {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_QuickMatch struct {
	QuickMatch *QuickMatch `protobuf:"bytes,1,opt,name=quick_match,json=quickMatch,proto3,oneof"`
}

type ClientMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type ClientMessage_Kick struct {
	Kick *Kick `protobuf:"bytes,3,opt,name=kick,proto3,oneof"`
}

type ClientMessage_StartGame struct {
	StartGame *StartGame `protobuf:"bytes,4,opt,name=start_game,json=startGame,proto3,oneof"`
}

type ClientMessage_PlayCard struct {
	PlayCard *PlayCard `protobuf:"bytes,5,opt,name=play_card,json=playCard,proto3,oneof"`
}

type ClientMessage_AddCard struct {
	AddCard *AddCard `protobuf:"bytes,6,opt,name=add_card,json=addCard,proto3,oneof"`
}

type ClientMessage_Pass struct {
	Pass *Pass `protobuf:"bytes,7,opt,name=pass,proto3,oneof"`
}

type ClientMessage_Bito struct {
	Bito *Bito `protobuf:"bytes,8,opt,name=bito,proto3,oneof"`
}

type ClientMessage_Ready struct {
	Ready *Ready `protobuf:"bytes,9,opt,name=ready,proto3,oneof"`
}

type ClientMessage_Leave struct {
	Leave *Leave `protobuf:"bytes,10,opt,name=leave,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,11,opt,name=ping,proto3,oneof"`
}

func (*ClientMessage_QuickMatch) isClientMessage_Payload() {}

func (*ClientMessage_Subscribe) isClientMessage_Payload() {}

func (*ClientMessage_Kick) isClientMessage_Payload() {}

func (*ClientMessage_StartGame) isClientMessage_Payload() {}

func (*ClientMessage_PlayCard) isClientMessage_Payload() {}

func (*ClientMessage_AddCard) isClientMessage_Payload() {}

func (*ClientMessage_Pass) isClientMessage_Payload() {}

func (*ClientMessage_Bito) isClientMessage_Payload() {}

func (*ClientMessage_Ready) isClientMessage_Payload() {}

func (*ClientMessage_Leave) isClientMessage_Payload() {}

func (*ClientMessage_Ping) isClientMessage_Payload() {}

type MatchStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStarted) Reset() {
	*x = MatchStarted{}
	mi := &file_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStarted) ProtoMessage() {}

func (x *MatchStarted) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStarted.ProtoReflect.Descriptor instead.
func (*MatchStarted) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{12}
}

func (x *MatchStarted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type Kicked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kicked) Reset() {
	*x = Kicked{}
	mi := &file_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kicked) ProtoMessage() {}

func (x *Kicked) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kicked.ProtoReflect.Descriptor instead.
func (*Kicked) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{13}
}

func (x *Kicked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LeftAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeftAck) Reset() {
	*x = LeftAck{}
	mi := &file_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeftAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftAck) ProtoMessage() {}

func (x *LeftAck) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftAck.ProtoReflect.Descriptor instead.
func (*LeftAck) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{14}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{15}
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_QueueState
	//	*ServerMessage_RoomState
	//	*ServerMessage_GameState
	//	*ServerMessage_Error
	//	*ServerMessage_Kicked
	//	*ServerMessage_MatchStarted
	//	*ServerMessage_LeftAck
	//	*ServerMessage_Pong
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{16}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetQueueState() *QueueState {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_QueueState); ok {
			return x.QueueState
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomState() *RoomState {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RoomState); ok {
			return x.RoomState
		}
	}
	return nil
}

func (x *ServerMessage) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetKicked() *Kicked {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Kicked); ok {
			return x.Kicked
		}
	}
	return nil
}

func (x *ServerMessage) GetMatchStarted() *MatchStarted {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_MatchStarted); ok {
			return x.MatchStarted
		}
	}
	return nil
}

func (x *ServerMessage) GetLeftAck() *LeftAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_LeftAck); ok {
			return x.LeftAck
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_QueueState struct {
	QueueState *QueueState `protobuf:"bytes,1,opt,name=queue_state,json=queueState,proto3,oneof"`
}

type ServerMessage_RoomState struct {
	RoomState *RoomState `protobuf:"bytes,2,opt,name=room_state,json=roomState,proto3,oneof"`
}

type ServerMessage_GameState struct {
	GameState *GameState `protobuf:"bytes,3,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type ServerMessage_Kicked struct {
	Kicked *Kicked `protobuf:"bytes,5,opt,name=kicked,proto3,oneof"`
}

type ServerMessage_MatchStarted struct {
	MatchStarted *MatchStarted `protobuf:"bytes,6,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type ServerMessage_LeftAck struct {
	LeftAck *LeftAck `protobuf:"bytes,7,opt,name=left_ack,json=leftAck,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,8,opt,name=pong,proto3,oneof"`
}

func (*ServerMessage_QueueState) isServerMessage_Payload() {}

func (*ServerMessage_RoomState) isServerMessage_Payload() {}

func (*ServerMessage_GameState) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

func (*ServerMessage_Kicked) isServerMessage_Payload() {}

func (*ServerMessage_MatchStarted) isServerMessage_Payload() {}

func (*ServerMessage_LeftAck) isServerMessage_Payload() {}

func (*ServerMessage_Pong) isServerMessage_Payload() {}

var File_session_proto protoreflect.FileDescriptor

var file_session_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0a, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a,
	0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x23, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x25,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66,
	0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x70, 0x61, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x69, 0x72,
	0x5f, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x25,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66,
	0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x22, 0x06, 0x0a,
	0x04, 0x42, 0x69, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x07,
	0x0a, 0x05, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22,
	0xac, 0x04, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x48,
	0x00, 0x52, 0x0a, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x36, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6b, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x63, 0x6b, 0x12, 0x37,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6f, 0x6f,
	0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x43, 0x61, 0x72,
	0x64, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x31, 0x0a,
	0x08, 0x61, 0x64, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x27, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x73,
	0x73, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x62, 0x69, 0x74,
	0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61,
	0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x62, 0x69,
	0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x2a,
	0x0a, 0x05, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63,
	0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x27,
	0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x4b, 0x69, 0x63, 0x6b, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x09, 0x0a, 0x07, 0x4c, 0x65, 0x66,
	0x74, 0x41, 0x63, 0x6b, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0xc1, 0x03, 0x0a,
	0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a,
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0a,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61,
	0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f,
	0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x6b, 0x69, 0x63, 0x6b,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63,
	0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x06, 0x6b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x40, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x65, 0x66,
	0x74, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6f,
	0x6f, 0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x66, 0x74, 0x41, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x65, 0x66, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x04,
	0x70, 0x6f, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x6f,
	0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x32, 0x54, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x45, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x66, 0x6f, 0x6f,
	0x6c, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61, 0x72,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x66, 0x6f, 0x6f, 0x6c, 0x63, 0x61,
	0x72, 0x64, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_session_proto_goTypes = []any{
	(*QuickMatch)(nil),    // 0: foolcard.v1.QuickMatch
	(*Subscribe)(nil),     // 1: foolcard.v1.Subscribe
	(*Kick)(nil),          // 2: foolcard.v1.Kick
	(*StartGame)(nil),     // 3: foolcard.v1.StartGame
	(*PlayCard)(nil),      // 4: foolcard.v1.PlayCard
	(*AddCard)(nil),       // 5: foolcard.v1.AddCard
	(*Pass)(nil),          // 6: foolcard.v1.Pass
	(*Bito)(nil),          // 7: foolcard.v1.Bito
	(*Ready)(nil),         // 8: foolcard.v1.Ready
	(*Leave)(nil),         // 9: foolcard.v1.Leave
	(*Ping)(nil),          // 10: foolcard.v1.Ping
	(*ClientMessage)(nil), // 11: foolcard.v1.ClientMessage
	(*MatchStarted)(nil),  // 12: foolcard.v1.MatchStarted
	(*Kicked)(nil),        // 13: foolcard.v1.Kicked
	(*LeftAck)(nil),       // 14: foolcard.v1.LeftAck
	(*Pong)(nil),          // 15: foolcard.v1.Pong
	(*ServerMessage)(nil), // 16: foolcard.v1.ServerMessage
	(*Card)(nil),          // 17: foolcard.v1.Card
	(*QueueState)(nil),    // 18: foolcard.v1.QueueState
	(*RoomState)(nil),     // 19: foolcard.v1.RoomState
	(*GameState)(nil),     // 20: foolcard.v1.GameState
	(*Error)(nil),         // 21: foolcard.v1.Error
}
var file_session_proto_depIdxs = []int32{
	17, // 0: foolcard.v1.PlayCard.card:type_name -> foolcard.v1.Card
	17, // 1: foolcard.v1.AddCard.card:type_name -> foolcard.v1.Card
	0,  // 2: foolcard.v1.ClientMessage.quick_match:type_name -> foolcard.v1.QuickMatch
	1,  // 3: foolcard.v1.ClientMessage.subscribe:type_name -> foolcard.v1.Subscribe
	2,  // 4: foolcard.v1.ClientMessage.kick:type_name -> foolcard.v1.Kick
	3,  // 5: foolcard.v1.ClientMessage.start_game:type_name -> foolcard.v1.StartGame
	4,  // 6: foolcard.v1.ClientMessage.play_card:type_name -> foolcard.v1.PlayCard
	5,  // 7: foolcard.v1.ClientMessage.add_card:type_name -> foolcard.v1.AddCard
	6,  // 8: foolcard.v1.ClientMessage.pass:type_name -> foolcard.v1.Pass
	7,  // 9: foolcard.v1.ClientMessage.bito:type_name -> foolcard.v1.Bito
	8,  // 10: foolcard.v1.ClientMessage.ready:type_name -> foolcard.v1.Ready
	9,  // 11: foolcard.v1.ClientMessage.leave:type_name -> foolcard.v1.Leave
	10, // 12: foolcard.v1.ClientMessage.ping:type_name -> foolcard.v1.Ping
	18, // 13: foolcard.v1.ServerMessage.queue_state:type_name -> foolcard.v1.QueueState
	19, // 14: foolcard.v1.ServerMessage.room_state:type_name -> foolcard.v1.RoomState
	20, // 15: foolcard.v1.ServerMessage.game_state:type_name -> foolcard.v1.GameState
	21, // 16: foolcard.v1.ServerMessage.error:type_name -> foolcard.v1.Error
	13, // 17: foolcard.v1.ServerMessage.kicked:type_name -> foolcard.v1.Kicked
	12, // 18: foolcard.v1.ServerMessage.match_started:type_name -> foolcard.v1.MatchStarted
	14, // 19: foolcard.v1.ServerMessage.left_ack:type_name -> foolcard.v1.LeftAck
	15, // 20: foolcard.v1.ServerMessage.pong:type_name -> foolcard.v1.Pong
	11, // 21: foolcard.v1.GameSession.Session:input_type -> foolcard.v1.ClientMessage
	16, // 22: foolcard.v1.GameSession.Session:output_type -> foolcard.v1.ServerMessage
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_common_proto_init()
	file_game_proto_init()
	file_session_proto_msgTypes[4].OneofWrappers = []any{}
	file_session_proto_msgTypes[11].OneofWrappers = []any{
		(*ClientMessage_QuickMatch)(nil),
		(*ClientMessage_Subscribe)(nil),
		(*ClientMessage_Kick)(nil),
		(*ClientMessage_StartGame)(nil),
		(*ClientMessage_PlayCard)(nil),
		(*ClientMessage_AddCard)(nil),
		(*ClientMessage_Pass)(nil),
		(*ClientMessage_Bito)(nil),
		(*ClientMessage_Ready)(nil),
		(*ClientMessage_Leave)(nil),
		(*ClientMessage_Ping)(nil),
	}
	file_session_proto_msgTypes[16].OneofWrappers = []any{
		(*ServerMessage_QueueState)(nil),
		(*ServerMessage_RoomState)(nil),
		(*ServerMessage_GameState)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Kicked)(nil),
		(*ServerMessage_MatchStarted)(nil),
		(*ServerMessage_LeftAck)(nil),
		(*ServerMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
